window.SICILY_MAPS = {
  palermo: [
    {n:'Delle Vittorie (hotel)', q:'Delle Vittorie Luxury Suites Via Bari 52 Palermo', note:'Home base · Jul 23–28'},
    {n:'Quattro Canti', q:'Quattro Canti Palermo', note:'Piazza Bellini area'},
    {n:'Palermo Cathedral', q:'Cattedrale di Palermo', note:'Daily from 7:00'},
    {n:'Norman Palace & Palatine Chapel', q:'Palazzo dei Normanni Palermo', note:'Jul 24 · book ahead'},
    {n:'Monreale Cathedral', q:'Duomo di Monreale', note:'Jul 24 · ~30 min by taxi'},
    {n:'La Martorana', q:'Chiesa della Martorana Palermo', note:'Mon–Sat 9:30–13:00'},
    {n:'San Cataldo', q:'Chiesa di San Cataldo Palermo', note:'Daily'},
    {n:'Santa Caterina', q:'Chiesa di Santa Caterina d\'Alessandria Palermo', note:'Daily 10:00–18:00'},
    {n:'Mercato Ballarò', q:'Mercato di Ballarò Palermo', note:'Mon–Sat to 14:00'},
    {n:'Capo Market', q:'Mercato del Capo Palermo', note:'Mon–Sat to 14:00'},
    {n:'Teatro Massimo', q:'Teatro Massimo Palermo', note:'Daily 9:30–19:00'},
    {n:'Seven Rooftop (Hotel Ambasciatori)', q:'Seven Restaurant Rooftop Bar Via Roma 111 Palermo', note:'Aperitivo · Jul 27'},
    {n:'Ferro di Cavallo', q:'Ferro di Cavallo Via Venezia 20 Palermo', note:'Dinner · Jul 23'},
    {n:'Osteria dei Vespri', q:'Osteria dei Vespri Piazza Croce dei Vespri 6 Palermo', note:'Dinner · Jul 24'},
    {n:'Antica Focacceria San Francesco', q:'Antica Focacceria San Francesco Palermo', note:'Dinner · Jul 25'},
    {n:'Palermo Centrale (station)', q:'Palermo Centrale railway station', note:'Cefalù train · car pickup nearby'}
  ],
  ortigia: [
    {n:'Ponte Santa Lucia', q:'Ponte Santa Lucia Siracusa', note:'Ortigia Walk starts here'},
    {n:'Temple of Apollo', q:'Tempio di Apollo Ortigia', note:'Walk stop 3'},
    {n:'Ortigia Street Market', q:'Mercato di Ortigia Via de Benedictis Siracusa', note:'Mon–Sat 7:00–14:00'},
    {n:'Siracusa Cathedral', q:'Duomo di Siracusa Piazza Duomo', note:'Piazza Duomo'},
    {n:'Fountain of Arethusa', q:'Fonte Aretusa Ortigia', note:'Walk ends here'},
    {n:'Algilà Ortigia Charme Hotel', q:'Algilà Ortigia Charme Hotel Via Vittorio Veneto 93', note:'Preferred hotel · TBD'},
    {n:'Ortea Palace Hotel', q:'Ortea Palace Hotel Siracusa', note:'Backup hotel'},
    {n:'Molo Sant\'Antonio parking', q:'Parcheggio Molo Sant\'Antonio Siracusa', note:'ZTL-free fallback lot'},
    {n:'Neapolis Archaeological Park', q:'Parco Archeologico della Neapolis Siracusa', note:'Jul 29 · Greek Theatre, Ear of Dionysius'},
    {n:'Ranieri', q:'Ristorante Ranieri Ortigia', note:'Dinner · Jul 28'},
    {n:'MOON', q:'MOON ristorante Ortigia Siracusa', note:'Dinner · Jul 29'},
    {n:'Noto Cathedral', q:'Cattedrale di Noto', note:'Jul 30'},
    {n:'Mamma Iabica', q:'Mamma Iabica Noto', note:'Lunch · Jul 30'},
    {n:'Calamosche Beach', q:'Spiaggia di Calamosche', note:'Jul 30'}
  ],
  taormina: [
    {n:'Villa Taormina (hotel)', q:'Hotel Villa Taormina Via Tommaso Fazzello 39 Taormina', note:'Home base · Jul 31–Aug 5'},
    {n:'Porta Catania', q:'Porta Catania Taormina', note:'Town Walk starts here'},
    {n:'Teatro Antico di Taormina', q:'Teatro Antico di Taormina', note:'Aug 1 · open 9:00'},
    {n:'Villa Comunale', q:'Giardini della Villa Comunale Taormina', note:'Aug 1'},
    {n:'Piazza IX Aprile', q:'Piazza IX Aprile Taormina', note:'Walk stop 8'},
    {n:'Palazzo Corvaja', q:'Palazzo Corvaja Taormina', note:'Walk ends nearby'},
    {n:'Da Onofrio (Pignolata Cannoli)', q:'La Pignolata Guinness Cannoli Viale Arcageta 15 Taormina', note:'Closed Wednesdays'},
    {n:'Al Giardino', q:'Al Giardino Via Bagnoli Croci 84 Taormina', note:'Call before going'},
    {n:'Médousa Bistrot', q:'Medousa Bistrot Via Sesto Pompeo 1 Taormina', note:'Dinner'},
    {n:'Incanto (Villa Ducale)', q:'Incanto Villa Ducale Taormina', note:'Rooftop dinner'},
    {n:'Principe Cerami', q:'Principe Cerami Via Santa Maria dei Greci 3 Taormina', note:'Dinner · Aug 2'},
    {n:'Osteria Villa Zuccaro', q:'Osteria Villa Zuccaro Corso Umberto 38 Taormina', note:'Final dinner option'},
    {n:'Giardini Naxos port (boat tour)', q:'Porto di Giardini Naxos', note:'Aug 3 · Sicily Active'},
    {n:'Mazzarò cable car', q:'Funivia Taormina Mazzarò', note:'Aug 3 · to Isola Bella'},
    {n:'Isola Bella', q:'Isola Bella Taormina', note:'Aug 3 · beach day'},
    {n:'Castelmola', q:'Castelmola', note:'Aug 4 · sunset'},
    {n:'Bar Turrisi', q:'Bar Turrisi Castelmola', note:'Almond wine & cannolo'},
    {n:'Madonna della Rocca', q:'Santuario Madonna della Rocca Taormina', note:'Stop on the way down'},
    {n:'Catania Airport (CTA)', q:'Aeroporto di Catania Fontanarossa', note:'Aug 5 · car drop-off'}
  ]
};
